# docker search mariadb
# docker pull mariadb/server:10.4
# docker run --name mariadbtest -e MYSQL_ROOT_PASSWORD=mypass -d mariadb/server:10.4
# https://mariadb.com/kb/en/installing-and-using-mariadb-via-docker/ 
